services:
  - type: web
    plan: free
    name: saichemile
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/mylovemoon/ChemileBot
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_URL
        sync: false
      - key: SUPPORT_GRP
        sync: false  
        
